export default function ArticleGrid() {
  const featuredArticles = [
    {
      id: 1,
      title: "The Rise of Multi-Engine AI Systems",
      excerpt: "How 8-engine consensus is changing content generation forever",
      category: "AI Research",
      readTime: "5 min read",
      isFeatured: true
    },
    {
      id: 2,
      title: "Ultra-Resilient Architecture Explained",
      excerpt: "Surviving multiple AI failures without compromising quality",
      category: "Engineering",
      readTime: "7 min read",
      isFeatured: false
    },
    {
      id: 3,
      title: "Prompt Engineering at Scale",
      excerpt: "Advanced techniques for multi-AI prompt optimization",
      category: "Tutorial",
      readTime: "4 min read",
      isFeatured: false
    },
    {
      id: 4,
      title: "Zero-Cost AI Infrastructure",
      excerpt: "Leveraging $5000+ free credits for production systems",
      category: "Infrastructure",
      readTime: "6 min read",
      isFeatured: false
    }
  ]

  return (
    <section className="py-16 bg-black">
      <div className="container mx-auto px-4">
        {/* Section Header */}
        <div className="flex items-center justify-between mb-12">
          <div>
            <h2 className="text-3xl lg:text-4xl font-bold text-white mb-4">
              Latest from our{' '}
              <span className="text-gradient">AI Engines</span>
            </h2>
            <p className="text-gray-400 text-lg">
              Premium content generated by our 8-engine consensus system
            </p>
          </div>
          <button className="hidden lg:flex items-center space-x-2 text-gray-400 hover:text-white transition-colors">
            <span>View All</span>
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
            </svg>
          </button>
        </div>

        {/* Articles Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {featuredArticles.map((article) => (
            <article
              key={article.id}
              className={`glass-card rounded-2xl overflow-hidden hover-lift ${
                article.isFeatured ? 'lg:col-span-2' : ''
              }`}
            >
              <div className={`flex flex-col ${article.isFeatured ? 'lg:flex-row' : ''}`}>
                {/* Image Placeholder */}
                <div className={`bg-gradient-to-br from-[#0066ff] to-[#8b5cf6] ${
                  article.isFeatured ? 'lg:w-1/2 h-64 lg:h-auto' : 'h-48'
                }`}></div>

                {/* Content */}
                <div className={`p-6 flex-1 ${
                  article.isFeatured ? 'lg:w-1/2' : ''
                }`}>
                  <div className="flex items-center space-x-4 mb-3">
                    <span className="px-3 py-1 bg-gray-800 text-gray-300 rounded-full text-sm font-medium">
                      {article.category}
                    </span>
                    <span className="text-gray-500 text-sm">{article.readTime}</span>
                  </div>

                  <h3 className={`font-bold text-white mb-3 ${
                    article.isFeatured ? 'text-2xl lg:text-3xl' : 'text-xl'
                  }`}>
                    {article.title}
                  </h3>

                  <p className="text-gray-400 mb-4 leading-relaxed">
                    {article.excerpt}
                  </p>

                  <button className="text-[#0066ff] hover:text-[#8b5cf6] transition-colors font-medium">
                    Read Full Article →
                  </button>
                </div>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  )
}
